comment ALGOL (ALGOL 60): algol hello.alg
comment ALGOL (Marst): marst hello.alg
comment ALGOL (Elliott): elliott-algol hello.alg
comment ALGOL (Burroughs): burroughs-algol hello.alg
comment ALGOL (GENIE): genie hello.alg
comment ALGOL (RRA): rra hello.alg
comment ALGOL (JOVIAL): jovial hello.alg
comment ALGOL (emulator): algol60 hello.alg

begin
    comment This is a hello world program in ALGOL;
    outstring(1, "Hello World!");
    outchar(1, 10)
end
